#!/bin/sh

#LINUX
CC				= gcc

RM				= rm -f

BASE_HOME = ../../../
SRC_HOME  = .

OUT_DIR   = .
DST_DIR   = $(BASE_HOME)/bin
INC_DIR   = $(BASE_HOME)/include
LIB_DIR   = $(BASE_HOME)/lib

OBJ       = o

#Fixed System Flag 
###################################
#              LIST               #
###################################
SYS_FIXED_FLAG  = AUTO

ENV = -Wall 

COPTS     = -lpthread -g #-O2 #-pg #+w2
IOPTS     = -I$(INC_DIR) -I../

POPTS     = $(DEBUG) $(DEBUG_TRC)

LIBS      = \
		$(BASE_HOME)/lib/librly.a\
		$(BASE_HOME)/lib/libtrn.a\
		$(BASE_HOME)/lib/libthr.a\
		$(BASE_HOME)/lib/libcom.a\


SRCS		= smulibInt_main.c \
			smulibInt_init.c \
			smulibInt_lh.c \
			smulibInt_timer.c \
			smulibInt_glob.c \
			smulibInt_sig.c \
			smulibInt_thblk.c \
			smulibInt_uh.c \
			smulib_api.c \
			test.c \

OBJS			= $(SRCS:.c=.o)

AOUT			= TEST

DEST			= ./

#
#---------------------------------------------------------------------
#
all:: $(AOUT) 

.SUFFIXES: .c .o
.c.o:
		$(CC) $(COPTS) $(ENV) $(LOPTS) $(IOPTS) $(POPTS) -c $<;

$(AOUT): $(OBJS)
		$(CC) $(COPTS) $(ENV) $(LOPTS) -o $(AOUT) $(IOPTS) $(POPTS) $(OBJS) $(LIBS);

install:
	cp -R ./smd ~/bin

clean:
	\rm -f $(OBJS) $(AOUT) core
