.SUFFIXEDS	: .c .o

#HP-UX
#CC			= cc

#LINUX
CC			= gcc

AR			= ar

INC_POS     = ../../include
INC         = -I$(INC_POS) -I../../include


LIBS		= $(SYS_LIB) $(USR_LIB)

#HP-UX
#F64         = -g -D_OS_HPUX_ +DD64 +w2
#CFLAGS		= -g $(OPT) $(DFLAG) $(F64) $(WFLAG) $(INC) $(LIBS)
#LINUX
#32BIT
#CFLAGS		= -Wall -g -m32 $(OPT) $(DFLAG) $(WFLAG) $(INC) $(LIBS)
#64BIT
CFLAGS		= -Wall -g -pg -m64 $(OPT) $(DFLAG) $(WFLAG) $(INC) $(LIBS)
#CFLAGS		= -Wall -g -m64 -O2 -finline-functions $(OPT) $(DFLAG) $(WFLAG) $(INC) $(LIBS)

SRCS		= thlib_thrd.c \
			  thlib_mutx.c \
			  thlib_cond.c \
			  thlib_tq.c \
			  thlib_pool.c \
			  poolTest.c \

OBJS		= $(SRCS:.c=.o)

TARGET_BASE = ../..

#TARGET		= libthlib.a
TARGET		= test
TARGET_DIR	= $(TARGET_BASE)/lib/

$(TARGET)	: $(OBJS)
		$(AR) rcv $@ $(OBJS)
		cp $(TARGET) $(TARGET_DIR)

all			: clean $(TARGET)

clean		: 
		rm -rf $(OBJS) $(TARGET) core 

dep 		: 
		makedepend -- $(CFLAGS) -- $(SRCS)

new			:
		$(MAKE) clean
		$(MAKE)
