#!/bin/sh

#LINUX
CC				= gcc

RM				= rm -f

BASE_HOME = ../..
SRC_HOME  = .

OUT_DIR   = .
DST_DIR   = $(BASE_HOME)/bin
INC_DIR   = $(BASE_HOME)/include
LIB_DIR   = $(BASE_HOME)/lib

OBJ       = o

#Fixed System Flag 
###################################
#              LIST               #
###################################
SYS_FIXED_FLAG  = AUTO

#ENV = -Wall  -DLOGLIB_DISP_ENV_LVL -DLOGLIB_DISP_ENV_FILE -DLOGLIB_DISP_ENV_LINE -DLOGLIB_DISP_ENV_TIME
ENV = -Wall  -DLOGLIB_DISP_ENV_LVL -DLOGLIB_DISP_ENV_TIME

COPTS     = -g -lpthread -luriparser -lmicrohttpd -lxml2 #-lcrypto #-pg #+w2
IOPTS     = -I$(INC_DIR) #-I/usr/include/libxml2

POPTS     = $(DEBUG) $(DEBUG_TRC)

LIBS      = \
		$(BASE_HOME)/lib/libsmu.a\
		$(BASE_HOME)/lib/librrl.a\
		$(BASE_HOME)/lib/librly.a\
		$(BASE_HOME)/lib/libtrn.a\
		$(BASE_HOME)/lib/liblog.a\
		$(BASE_HOME)/lib/libthr.a\
		$(BASE_HOME)/lib/libcom.a\


SRCS		= rbrlibInt_main.c \
			rbrlib_api.c \
			rbrlibInt_glob.c \
			rbrlibInt_init.c \
			rbrlibInt_svr.c \
			rbrlibInt_util.c \
			dbTest.c 

OBJS			= $(SRCS:.c=.o)

AOUT			= rbrTest 

DEST			= ./

#
#---------------------------------------------------------------------
#
all:: $(AOUT) 

.SUFFIXES: .c .o
.c.o:
		$(CC) $(COPTS) $(ENV) $(LOPTS) $(IOPTS) $(POPTS) -c $<;

$(AOUT): $(OBJS)
		$(CC) $(COPTS) $(ENV) $(LOPTS) -o $(AOUT) $(IOPTS) $(POPTS) $(OBJS) $(LIBS);\

clean:
	\rm -f $(OBJS) $(AOUT) core ;\
