#!/bin/sh

#HP-UX
#CC				= cc

#LINUX
CC				= gcc

RM				= rm -f
DEPEND			= makedepend
LINT			= lint

BASE_HOME = ../..
SRC_HOME  = .

OUT_DIR   = .
DST_DIR   = $(BASE_HOME)/bin
INC_DIR   = $(BASE_HOME)/include
LIB_DIR   = $(BASE_HOME)/lib

API_DIR   = $(BASE_HOME)/api/include
API_LIB_DIR = $(BASE_HOME)/api/lib

OBJ       = o

#Fixed System Flag 
###################################
#              LIST               #
###################################
SYS_FIXED_FLAG  = AUTO

ENV = -Wall 

#COPTS     = -g  -lpthread -lxml2 #-pg #+w2
COPTS     = -g #-lxml2 #-pg #+w2
IOPTS     = -I$(INC_DIR) -I$(API_DIR)

IHLROPTS  = -I. -I/usr/include/libxml2 -I/usr/local/opt/libxml2/include/libxml2/ 
IHLROPTS  += -DLOGLIB_ENB_LVL=3
IHLROPTS  += -DLOGLIB_DISP_ENV_LVL 
IHLROPTS  += -DLOGLIB_DISP_ENV_FILE 
IHLROPTS  += -DLOGLIB_DISP_ENV_LINE
IHLROPTS  += -DLOGLIB_DISP_ENV_TIME
#IHLROPTS  += -DLOGLIB_TOML_CONFIG_DISABLE
#IHLROPTS  += -DLOGLIB_XML_CONFIG_DISABLE
IHLROPTS  += -DLOGLIB_LOG

POPTS     = $(DEBUG) $(DEBUG_TRC) #-lxml2

LIBS      = \
		$(BASE_HOME)/lib/libthr.a\
		$(BASE_HOME)/lib/libcom.a\
		$(BASE_HOME)/lib/libtoml.a\
        -lxml2\


SRCS		= test.c \
			loglibInt_init.c \
			loglibInt_apnd.c\
			loglibInt_thrd.c\
			loglibInt_misc.c\
			loglibInt_load.c\
			loglibInt_loadXml.c\
			loglibInt_loadToml.c\
			loglibInt_glob.c\
			loglib_api.c\

OBJS			= $(SRCS:.c=.o)

AOUT			= test 

DEST			= ./

#
#---------------------------------------------------------------------
#
all:: $(AOUT) install

.SUFFIXES: .c .o
.c.o:
		$(CC) $(COPTS) $(ENV) $(LOPTS) $(IOPTS) $(POPTS) $(IHLROPTS) -c $<;

$(AOUT): $(OBJS)
		$(CC) $(COPTS) $(ENV) $(LOPTS) -o $(AOUT) $(IOPTS) $(POPTS) $(IHLROPTS) $(OBJS) $(LIBS);

install:

clean:
	\rm -f $(OBJS) $(AOUT) core
