.SUFFIXEDS	: .c .o

CC			= gcc

AR			= ar

INC         = -I../../include -I/usr/include/libxml2

DFLAG       = -DLOGLIB_LOG

CFLAGS		= -g -Wall -O2 -finline-functions -m64 $(DFLAG) $(INC)
#CFLAGS		= -g -Wall -m64 $(DFLAG) $(INC)

SRCS		= loglibInt_init.c \
			  loglibInt_apnd.c\
			  loglibInt_thrd.c\
			  loglibInt_misc.c\
			  loglibInt_load.c\
			  loglibInt_loadXml.c\
			  loglibInt_loadToml.c\
			  loglibInt_glob.c\
			  loglib_api.c\

OBJS		= $(SRCS:.c=.o)

TARGET_BASE = ../..

TARGET		= liblog.a
TARGET_DIR	= $(TARGET_BASE)/lib/
TARGET_INC  = $(TARGET_BASE)/include/

$(TARGET)	: $(OBJS)
		$(AR) rcv $@ $(OBJS)

all			: clean $(TARGET)

install     :
	    mkdir -p $(TARGET_DIR)
		mkdir -p $(TARGET_INC)
		cp $(TARGET) $(TARGET_DIR)
		cp loglib.h $(TARGET_INC)
		cp loglib.x $(TARGET_INC)

clean		: 
		rm -rf $(OBJS) $(TARGET) core 

dep 		: 
		makedepend -- $(CFLAGS) -- $(SRCS)

new			:
		$(MAKE) clean
		$(MAKE)
