[[LOG_CFG]]
#name = "test_cfg"

  [[LOG_CFG.LOG]]
    name = "test2"
    log_level = 2
    write_thread_flag = "true"

    [[LOG_CFG.LOG.APPENDER]]
      type = "file"
      name = "file_appender"
      display_level = "false"
      display_file = "false"
      display_line = "false"
      display_time = "true"
      log_path = "./log"
      log_name = "test"
      max_log_size = 199

    [[LOG_CFG.LOG.APPENDER]]
      type = "syslog"
      name = "syslog_appender"
      display_level = "false"
      display_file = "false"
      display_line = "true"
      display_time = "true"
      facility = LOG_LOCAL0

    [[LOG_CFG.LOG.APPENDER]]
      type = "stdout"
      name = "stdout_appender"
      display_level = "true"
      display_file = "false"
      display_line = "true"
      display_time = "true"
      std_type = "stderr"
      #std_type = "stdout"

