#ifndef _SMD_USER_H_
#define _SMD_USER_H_

#define SMD_PROC_NAME_MAX_LEN 1024

#define SMD_MSG_CODE_REG_REQ    1
#define SMD_MSG_CODE_REG_CFM    2
#define SMD_MSG_CODE_HB_REQ     3
#define SMD_MSG_CODE_HB_CFM     4
#define SMD_MSG_CODE_TERM_REQ   5
#define SMD_MSG_CODE_TERM_CFM   6
#define SMD_MSG_CODE_TERM_IND   7
#define SMD_MSG_CODE_TERM_RSP   8

#define SMD_MSG_RSLT_CODE_SUCC  1
#define SMD_MSG_RSLT_CODE_FAIL  2
#define SMD_MSG_RSLT_CODE_REREG 3

#endif /* _SMD_USER_H_ */
